### ISSUE TITLE
Add script or macro for multiple profiles

### ISSUE THREAD

**Issue by mbrady4597** [JiMcNulty/FDC#8]
I think one of the biggest reasons this hasn't seen more widespread adoption is that it is cumbersome to switch between profiles for different printing temperatures or different setups such as open vs closed enclosure. Adding a script to allow switching between profiles such as how bed mesh works natively in klipper would be a huge improvement. I think it might also be possible to implement this using a macro in klipper but it would probably be a bit more involved for the end user.

**Comment by JiMcNulty** [comment]
Thanks for taking the time to share your thoughts, really appreciate it
1. IMO, switching profile is not a big deal, takes me a few seconds
2. The solution is not widespread because people are taken aback by location of the needed sensor
3. Having said that, I did plan to develop support for multiple profiles (along with other features) if the project was widely used, as it's not currently the case the motivation is lacking, and I won't have the time to do so in the coming months anyhow.
4. Also there is always the possibility of someone that want to contribute to the project and add this feature, It's open source :)

Thanks again for caring and I hope FDC helped you get perfect layers!
